# @package _global_

# the file is adopted from
# https://github.com/pdebench/PDEBench/blob/main/pdebench/data_gen/configs/radial_dam_break.yaml
defaults:
  - _self_

# save work dir, since hydra overrides it by default
work_dir: ${hydra:runtime.cwd}
data_dir: data
output_path: 1D_swp_128_per
name: 1d_periodic_128
test: False

sim:
  T_end: 0.128  # 1.28  # 1.0
  n_time_steps: 128  # 100
  xdim: 128
  gravity: 1.0
  init_u: 0.0
  n2: 3
  lambdas: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  gammas: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  seed: '???'
