model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "epoch" # name of the logged metric which determines when model is improving
  mode: "max"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch"
  auto_insert_metric_name: False

plotting:
  _target_: callbacks.custom_callbacks.PlotDiffusionTrajectory
  num_samples: 5 # number of samples to plot
  log_every: 50 # save plots every n epochs

save_samples:
  _target_: callbacks.custom_callbacks.SaveGeneratedSamples
  num_samples: 5 # number of samples to plot
  dirpath: "samples/"