defaults:
  - model: fnostatereconstr2d
  - datamodule: datamodule_abs_coord
  - trainer: default
  - callbacks: default.yaml
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - _self_
seed: 0
name: fnostatereconstrabs2d
system: swe
logs_root_folder: ""
dataroot: data
subname: ""
ckpt_path: null
hydra:
  sweep:
    dir: ${logs_root_folder}logs/sweepruns/${name}${subname}${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    sampler:
      seed: 0
    direction: minimize
    study_name: fnostatereconstrabs2d
    storage: null
    n_trials: 15
    n_jobs: 2
  run:
    dir: ${logs_root_folder}logs/runs/${name}${subname}${now:%Y-%m-%d-%H-%M-%S}