defaults:
  - model: oformer_t
  - datamodule: datamodule_oformer_t
  - trainer: trainer_oformer
  - callbacks: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - _self_
seed: 1
name: oformer_1d
system: swe
logs_root_folder: ""
dataroot: data
subname: ""
ckpt_path: null
hydra:
  sweep:
    dir: ${logs_root_folder}logs/sweepruns/${name}${subname}${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    sampler:
      seed: 0
    direction: minimize
    study_name: oformer_1d
    storage: null
    n_trials: 15
    n_jobs: 2
  run:
    dir: ${logs_root_folder}logs/runs/${name}${subname}${now:%Y-%m-%d-%H-%M-%S}