_target_: datamodules.pl_oformer_datamodule.PlOformerSwpDatamodule
name: datamodule_t
train_path: data/1D_swp_NA_NA.h5
val_path: data/1D_swp_NA_NA.h5
test_path: data/1D_swp_NA_NA.h5
return_abs_coords: True
return_grid: False
norm_x: True
norm_t: True
norm_input: True
norm_target: True
add_t: True
flip_xy: False
const_norm_stats: True
use_theta: False
use_tar_ic: False
train_2d: True

num_workers: 10
batch_size: 16