name: ddim_1_sample
type: ddim
timesteps: 50
skip_type: uniform
eta: 0.0
n_samples: 1
n_repeat: 5
n_time_h: 128
n_time_u: 0
return_last: True
select_by_pde: False
use_gt_pde_select: True
guide_dx: False
w: 0.0
plot_scaled: False