name: edm
type: edm
timesteps: 50
sigma_min: 0.002
sigma_max: 80
rho: 7
S_churn: 15.0  # includes stochasticity in the model
S_min: 0
S_max: 'inf'
S_noise: 1
n_samples: 5
n_repeat: 2
n_time_h: 0
n_time_u: 128
return_last: True
select_by_pde: False
use_gt_pde_select: True
guide_dx: False
w: 0.0
plot_scaled: False